lib/yummy_web/router.ex
defmodule YummyWeb.Router do
  use YummyWeb, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", YummyWeb do
    pipe_through :browser # Use the default browser stack

    get "/recipes/search", RecipeController, :search
    resources "/recipes", RecipeController do
      resources "/comments", CommentController, only: [:create]
    end

    get "/", RecipeController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", YummyWeb do
  #   pipe_through :api
  # end
end

lib/yummy_web/views/coherence/layout_view.ex
defmodule YummyWeb.Coherence.LayoutView do
  use YummyWeb, :view
end

lib/yummy_web/views/layout_view.ex
defmodule YummyWeb.LayoutView do
  use YummyWeb, :view
end

lib/yummy_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Yummy!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
        <header class="header">
      <div class="container">
        <nav class="navbar is-primary" role="navigation">
          <div class="navbar-brand">
            <%= link to: recipe_path(@conn, :index), class: "navbar-item" do %>
              <%= img_tag static_path(@conn, "/images/yummy-icon.png"), class: "yummy-icon" %>
            <% end %>
          </div>
          <div class="navbar-menu">
            <div class="navbar-end">
              <%= coherence_links(@conn, :layout) %>
            </div>
          </div>
        </nav>
      </div>
    </header>

    <main role="main">
      <section class="section">
        <div class="container">
          <div class="columns">
            <div class="column is-offset-2 is-8">
              <%= if get_flash(@conn, :notice) do %>
                <p class="notification is-primary" role="alert"><%= get_flash(@conn, :notice) %></p>
              <% end %>
              <%= if get_flash(@conn, :error) do %>
                <p class="notification is-danger" role="alert"><%= get_flash(@conn, :error) %></p>
              <% end %>

              <%= render @view_module, @view_template, assigns %>
            </div>
          </div>
        </div>
      </section>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>