lib/yummy_web/router.ex
defmodule YummyWeb.Router do
  use YummyWeb, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", YummyWeb do
    pipe_through :browser # Use the default browser stack

    get "/recipes/search", RecipeController, :search
    resources "/recipes", RecipeController do
      resources "/comments", CommentController, only: [:create]
    end

    get "/", RecipeController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", YummyWeb do
  #   pipe_through :api
  # end
end

lib/yummy/recipes/comment.ex
defmodule Yummy.Recipes.Comment do
  use Ecto.Schema
  import Ecto.Changeset
  alias Yummy.Recipes.{Comment, Recipe}
  alias Yummy.Accounts.User


  schema "comments" do
    field :body, :string
    belongs_to :recipe, Recipe
    belongs_to :user, User

    timestamps()
  end

  @doc false
  def changeset(%Comment{} = comment, attrs \\ %{}) do
    comment
    |> cast(attrs, [:body, :user_id, :recipe_id])
    |> validate_required([:body])
  end
end

lib/yummy_web/controllers/comment_controller.ex
defmodule YummyWeb.CommentController do
  use YummyWeb, :controller

  alias Yummy.Recipes
  alias Yummy.Recipes.Recipe

  plug Coherence.RequireLogin

  def create(conn, %{"comment" => comment_params, "recipe_id" => recipe_id }) do
    recipe = Recipe
      |> Repo.get!(recipe_id)
      |> Repo.preload([{:comments, :user}, :user])

    case current_user(conn) |> Recipes.create_comment(recipe, comment_params) do
      {:ok, _comment} ->
        conn
        |> put_flash(:info, "Le commentaire à bien été posté.")
        |> redirect(to: "#{recipe_path(conn, :show, recipe)}#comments")
      {:error, %Ecto.Changeset{} = comment_changeset} ->
        render(conn, YummyWeb.RecipeView, "show.html", recipe: recipe, comment_changeset: comment_changeset)
    end
  end
end

lib/yummy_web/views/comment_view.ex
defmodule YummyWeb.CommentView do
  use YummyWeb, :view
end

lib/yummy_web/templates/comment/_comments.html.eex
<%= unless Enum.empty?(@recipe.comments) do %>
  <div class="comments" id="comments">
    <h4 class="title is-4">Commentaires</h2>
    <ul>
      <%= for comment <- @recipe.comments do %>
        <li class="comment">
          <div class="comment-content"><%= comment.body %></div>
          <div class="comment-info">
            <span>Par <%= comment.user.name %> le </span>
            <span><%= Timex.format!(comment.inserted_at, "%d/%m/%Y", :strftime) %></span>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

lib/yummy_web/templates/comment/_new.html.eex
<%= if logged_in?(@conn) do %>
  <div class="new-comment">
    <h4 class="title is-4">Nouveau Commentaire</h3>

    <%= form_for @comment_changeset, recipe_comment_path(@conn, :create, @recipe), fn f -> %>
      <%= input f, :body, using: :textarea, input_html: [rows: 4], label: false %>

      <div class="field">
        <%= submit "Soumettre", class: "button is-primary" %>
      </div>
    <% end %>
  </div>
<% end %>